### ISSUE TITLE
Routing and HTTP Verbs

### ISSUE THREAD

**Issue by leostera** [kilianc/node-apiserver-router#1]
Hi there,

I was trying to use your node-apiserver but by the time I wanted to define routes I had to start checking this package to see how am I supposed to define specific routes depending on the HTTP Verbs.

Is there a nice, well defined way of doing so? I really like the fact it auto generates the routes based on the objects properties names but sometimes a property name is not really meaningful (or too verbose) for being used as an endpoint, and also switching the request method doesn't fit the bill. I find it even more likely than middleware will get as deep as http verb specific with much ease if the model for the resources is taken in account differently. Something like this:

Enable multiple verbs for a single middleware
ApiServer.use("regex",middleware1,["post","get"])

Or fine grain the middlewares depending on the verb
ApiServer.use.post("regex",middleware2)
ApiServer.use.put("regex",middleware3)
ApiServer.use.get("regex",middleware4)

Don't know how fast it would be but a model where a Resource has diferent get,post,put,del,head,options methods sounds like a better approach to building -from a developer point of view- RESTful (not SOAP, *-RPC, whatever) API services. Do you think something [like this](https://gist.github.com/2623257) might get implemented?

I am actually volunteering.

**Comment by kilianc** [comment]
First of all, Hi :wave:

> Enable multiple verbs for a single middleware
> `ApiServer.use("regex",middleware1,["post","get"])`

This is a very simple to implement without touching the routing. Every middleware ring should be replaced by a HTTP verb precondition.

It should be implemented [here](https://github.com/kilianc/node-apiserver/blob/master/lib/apiserver.js#L53) wrapping the middleware around a function, we can talk about this more if you open an issue on the apiserver repo, I want absolutely add this on 0.2.1.

I don't like this:

> Or fine grain the middlewares depending on the verb
> ApiServer.use.post("regex",middleware2)

There are so many points to take care about the _RESTful_ thing, I am trying to avoid to use this term in order to save me from RESTful purists' slaps. Your idea is good, was one of the possibles paths when I wrote the v0.2.x branch but there is some problem with this:
- the scope _(this)_ of your API end point is not clear.
- a method should accomplish only one thing.
- the routing should be implicit.
- why using a class as an object?

I really like your example anyway, and I am been looking for something that follows the apiserver philosophy and accomplish this from the beginning, so I am glad to accept proposals.

In the road map there is a routing/rewriting system, but I am trying to figure out what is the right place for this kind of stuff. Router? Module itself? Middleware? Maybe a rails style `routes.rb`?

P.S. you can rewrite the router and make it acts like this:

``` js
// /users/login
Users.prototype.getLogin = function (...)
Users.prototype.postLogin = function (...)
```

**Comment by leostera** [comment]
Hi, 

I am taking a look at the middleware multipel verb enabling now. And yep, I do understand your point on the _RESTful_ purists slaps. I'm not a purist _per se_ but I just wandered if the actual way of defining the resources was the best available. On the stuff you pointed out:
- the scope (_this_) of your API end point is not clear.
  I don't understand _this_, you mean it programatically?
- a method should accomplish only one thing.
  Well, indeed. If you track your object and go to the proper subobject (resource User.login) there is one method for each verb you want to handle, and each method takes care of only one set of actions related to that verb, that's pretty much "only one thing". If we get purists over here we'll probably end up with lots of different post's, put's or delete's that get handled from a big post/put/delete wrapper.
- the routing should be implicit.
  I have to admit I don't completely agree about implicit routing. Explicit is better than implicit, not always but in my experience in most of the cases it is. Perhaps it should be defined in a more centric location, like routes.rb/urls.py, I haven't had any problems doing resource based API's with Django that way. I do still think that if you plan on making implicit route building based on resources you should allow the developer to redefine the name of the resource. What if someone prefers underscores to camel case or neither of those?
- why using a class as an object?
  I wasn't actually using a class as an object. Just defined a class. That class might as well be instantiated with different parameters depending on the API Version, or re-instantiated whenever needed, or any other sort of functionality we might need. What's more, most of the resources will have a bunch of common functionality and attributes that could easily be modeled with a little OOP. I'm not saying everything should be done using that approach, but if it makes sense to treat specific resources as objects then it makes sense to generalize them as classes.

So yes, I guess having my class methods named as get/post/put/delete+Endpoint will have to do right now. [Here's a last gist](https://gist.github.com/2623966) on a more Django-ish routing and the first approach I took to routing.

**Comment by kilianc** [comment]
> I don't understand this, you mean it programatically?

Yes take a look a the module example [here](https://github.com/kilianc/node-apiserver#modules-examples), a must is that every endpoint is executed within the scope object, this mean that `this === apiModule`

Defining HTTP verbs as method makes sense, but not that way. Marak wrote [something like this](https://github.com/Marak/webservice.js/blob/master/examples/sample_modules/demoModule.js) but I don't really like it...

> Well, indeed. If you track your object and go to the proper subobject (resource User.login) there is one method for each verb you want to handle

Totally agree with this, but I don't like this way to use the prototype chain...
Maybe the point here is, **we really need a prototype**?

``` js
UsersResource.prototype.login = {
  get: function(res, req) {},
  post: function(res, req) {}
};
```

P.S. I am very OOP addicted.
P.P.S. Can you use plain js please?

**Comment by leostera** [comment]
Ok, that Marak thing was almost physically painful. Perhaps a prototype isn't needed, but for clarity's sake (and nice, oo extensibility) we could as well have it done.

I'd be glad to have a Resource prototype/class from where to inherit, that offers a basic structure for me to extend, but that is customizable enough for me to alter. Of course there is a fine line between awfully designed classes and permissive ones, but given the time and effort we might as well get a really cool Resource structure that makes us all get better web services done faste.

I'll try to do more plainer js.

**Comment by kilianc** [comment]
I want to think about it a bit. I know that we should go in that direction but I don't know how yet.

What do you think about [this](http://symfony.com/doc/current/book/routing.html) ?
And [this](http://guides.rubyonrails.org/routing.html) ?

It seems all too slow to me, but this looks pretty good: `:module/:version/:method` and I will probably add this as configuration param to the router for the default routing, so you can turn on/off versioning and add static labels etc.

**Comment by leostera** [comment]
We should definitely try at least in a experimental branch and see how that goes.

First one is ok as long as we stick to a YAMLish syntax. The second link is a great idea.

**Comment by kilianc** [comment]
One of the big problem is that the number of the iteration the router has to do to check the routes, is directly proportional to the number of routes. This means, bigger is the project slowest it will be. I don't like that, this is why I cache all the routes.

```
this.routes[req.pathname] // damnly fast
```

I don't see any different possible implementation from a "loopish / per request" one, I will check the rails/symfony router source.

**Comment by kilianc** [comment]
Another thought is that coupling "explicit routes" and source code, is not a good idea. I want to able to write a signup / signin module and use it in different projects, being able to change routes without touching the code.

Keeping routing and actions decoupled makes room for new ideas as well, storing routes into a database for example, or an hot reload without restarting the server.

**Comment by leostera** [comment]
So you are definitely going for a Django-ish kinda thing.

That's good too, I like Django's way of matching RegEx patterns (that allow parameter-ing thru named groups) to either specific functions or classes. Perhaps what you could try is 

``` coffeescript
routes.add
 [ /^home/<name>(\w*)/, ResourceClass.endPoint , options, autoEnable ]
 [ regex, ResourceClass.endPoint, options, autoEnable ]
```

And of course, those endpoints implement different http verbs.

**Comment by kilianc** [comment]
Exactly, this will allow core/modules intefaces to remain the same :beers:

Anyway there is a problem, if we add named arguments to the route (and I really want to do it) we are delegating the router to deal with the request, this is not good. We should avoid this kind of dependencies.

Now the core takes care of parsing the request querystring and this makes really sense, and should remain the same. We should think a great way to decouple these 2 things.

``` js
Router.prototype.get(request, response, pathname) {
  // do stuff and attach the querystring object with the regex values
}
```

or move move the querystring parsing (this line)

``` js
request.querystring = qs.parse(request.parsedUrl.search.replace(/^\?/, ''))
```

below the router and then do an object merge. (explicit qs should has highest priority)

P.S. what `autoEnable` is about? seems useless!

**Comment by leostera** [comment]
I thought of autoEnable as a flag defaulted true but that can be set as false so you can add a route but not use it. Seems pointless but it might be the case that you want an specific route to be there (and thus, match) but not to do anything just yet.

What about ignoring the named group in the regex until the regex is matched and then, since we already have the full querystring, parse it within the request object and generate a params object before it get's passed to the proper http verb method on the resource? 

So you match, don't do anything with the groups just yet, and once you are passing the request to the method, parse it.

**Comment by kilianc** [comment]
> And of course, those endpoints implement different http verbs.

Do you mean that every endpoint should implement 3 functions (like in your gist) ? I was thinking about something like this instead:

``` js
router.loadFile('./routes.yml')
router.add(['GET','POST'], '/users/:id/:verbose', 'users#showById')
router.add('GET', '/users_verbose/:id/', 'users#showById', { verbose: true })
```

not sure about the arguments order

> What about ignoring the named group in the regex until the regex is matched and then, since we already have the full querystring, parse it within the request object and generate a params object before it get's passed to the proper http verb method on the resource?

Yes, of course after the match, but do you mean keep `params` for routes params and `querystring` for querystring? In this case I disagree, is just an apache like rewrite rule, we just need a querystring obj

**Comment by kilianc** [comment]
and whit a default route

``` js
router.defaultRoutes(Boolean)
```

``` yaml
#stolen by symfony routing
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
```

**Comment by leostera** [comment]
Routes shouldn't be outside the code, using routes in the code might prove useful for iu18 or other stuff, and makes it clearer. So, if u ask me, loading a routes.yaml file with routes is out of the question.

The second thing thou looks nice enough. I'd have liked only to pass the Resource end-point and let it handle different verbs like in

``` javascript
SomeResource.prototype.endpoint.get = function (req, res, options) {
  // some code
}

SomeResource.prototype.endpoint.post = function (req, res, options) {
  // some code
}
```

No i meant replacing the querystring for the params object so its easily usable:

``` javascript
//...
params.user_id
params.verbosity_level
//...
```

**Comment by kilianc** [comment]
> Routes shouldn't be outside the code, using routes in the code might prove useful for iu18 or other stuff, and makes it clearer. So, if u ask me, loading a routes.yaml file with routes is out of the question.

Me too, but it would be great for other people, so maybe I will bump it later :)

> The second thing thou looks nice enough. I'd have liked only to pass the Resource end-point and let it handle different verbs like in

``` js
// I don't like this, but I can't see other ways than this.
SomeResource.prototype.endpoint = {}

// The router should bind the <VERB> method to the resource object, in order to have
// the `this` keyword pointing to the resource object itself
SomeResource.prototype.endpoint.get = function (req, res, options) {
  // some code
}
```

What about this:

``` js
SomeResource.prototype.get.endpoint = function (req, res, options) {
  // some code
}
SomeResource.prototype.post.endpoint = function (req, res, options) {
  // some code
}
```

We can use a parent constructor to create the verbs objects, or an utility function like this:

``` js
var SomeResource = apiserver.createModule()
```

> No i meant replacing the querystring for the params object so its easily usable

Ok we are on the same boat

**Comment by leostera** [comment]
``` javascript
endpoint_1 = {
    get: function(req, res, options) {
        //code
    }

    post: function(req, res, options) {
        //code
    }

//......more code!
}

SomeResourceInstance.createEndpoint(endpoint_1) //perhaps array compatible, too
```

Isn't it neat, well encapsulated and readable/maintainable? One could have a resource folder with each separate endpoint defined and all created inside a resource in a single index.js / index.coffee. Meaning loosy couple-ness all around, meaning reusable/extensible endpoints, meaning infinite endpoint coolness.

Totally a `apiserver.createModule` function would be awesome and it should do a bit of a magic binding trick to let the this still be the apiserver when inside each http verb function for the endpoint. That's when we might prove clever and make something cool. The key would be in the createEndpoint fun.

**Comment by leostera** [comment]
In fact if u ask me, the only reason I'm using Restify now instead of APIServer is because of the routing.

I'm starting a quite big REST Service so if we make this happen for say this weekend, I'll be glad to seriously use and collaborate in the development.

I've already forked the router, once we define exactly what we are going to do, let's split tasks and get 'em done.

**Comment by kilianc** [comment]
I will work on this tonight and I'll let you know, you should use the develop branch for a while... :)

**Comment by kilianc** [comment]
What about using XRegExp? JS doesn't support named groups so I was opting for a classic

```
"/users/:id/:verbose"
```

but if you want to use a regular expression you will end up to have unnamed parameters, and it sucks. Depending on a third party module for regular expressions sucks too...

**Comment by leostera** [comment]
What about this:

``` coffeescript
shouldBe =
  id:
    type: Number
    min: 0
    max: 999
  name: String

routes.add
  [ "/home/:id/:name/", shouldBe, ResourceClass.endPoint , options, autoEnable ]
```

Of course it will be optional to pass that literal, but supposing it is passed, it should be used to check for the params type/length/etc (even perhaps a regex) to be valid or not.

**Comment by kilianc** [comment]
This is too far :)
I really want to get to the point that will allow us to generate an test-console for our API based on routes and params definition. We will figure it out.

I am going to use XRegExp for complex routing :)

**Comment by kilianc** [comment]
I am working on this (80% done), but I have some design issue to solve. I will push an experimental branch in few days.

You can start writing your router in the while, now the `get` method accept the request object so you can modify your module to have multiple http verbs.

P.S. I am very satisfied about the results, can't wait to share the code

**Comment by kilianc** [comment]
@leostera look at the experimental branch and the [next version examples](https://github.com/kilianc/node-apiserver/tree/develop/examples).
Next release should satisfy all your needs without breaking anything.

I need some day to update the docs of the router and bump to v0.2.0, then I will bump ApiServer to v0.2.2 too

**Comment by leostera** [comment]
This looks awesome. If you need any help just let me know and I'll see what I can do.

**Comment by kilianc** [comment]
> This looks awesome.

I am glad you liked it :tada:

> If you need any help just let me know and I'll see what I can do.

I will open issues as soon I get new ideas, so if you want to play around feel free to fork and pull request, also it will be awesome to have more examples, and a real benchmark!

**Comment by leostera** [comment]
Sure, I'll fork it right now. Probably will be digging it this weekend thou, but expect new issues! =)
